---
- name: Debug group and username variables
  debug:
    msg:
      - "group: '{{ group | default('not set') }}'"
      - "username: '{{ username | default('not set') }}'"

- name: Create a group if it does not exist
  group:
    name: "{{ group | default(username) }}"
    state: present
  when: group | default(username) != ''

- name: Create a user account
  user:
    name: "{{ username }}"
    password: "{{ password | default('') }}"
    home: "{{ home_dir }}"
    shell: "{{ shell }}"
    group: "{{ group | default(username) }}"
    state: present
  when: username != ''
