# tasks file for iteasy.ansible.roles.account_manager
---
- name: Set group_name to group or username
  set_fact:
    group_name: "{{ group | default(username) }}"
  
- name: Debug the group_name
  debug:
    msg: "group_name is set to: {{ group_name }}"

- name: Create a group if it does not exist
  group:
    name: "{{ group_name }}"
    state: present

- name: Create a user account
  user:
    name: "{{ username }}"
    password: "{{ password | default('') }}"
    home: "{{ home_dir }}"
    shell: "{{ shell }}"
    group: "{{ group_name }}"
    state: present
