---
# raw_tasks.yml - Create User

- name: Set group_name to group or username
  set_fact:
    group_name: "{{ group if group is defined and group != '' else username }}"

- name: Set home_dir to default if not defined or empty
  set_fact:
    home_dir: "{{ home_dir if home_dir is defined and home_dir != '' else '/home/' ~ username }}"

- name: Set shell to default if not defined or empty
  set_fact:
    shell: "{{ shell if shell is defined and shell != '' else '/bin/bash' }}"

- name: Generate a random password if not provided
  set_fact:
    password: "{{ password | default(lookup('password', '/dev/null length=16 chars=ascii_letters,digits')) }}"

- name: Debug the group_name, home_dir, shell, and password
  debug:
    msg:
      - "group_name is set to: {{ group_name }}"
      - "home_dir is set to: {{ home_dir }}"
      - "shell is set to: {{ shell }}"
      - "password is set to: {{ password }}"

- name: Check if group exists
  raw: "getent group {{ group_name }}"
  register: group_check
  failed_when: false
  changed_when: false

- name: Create the group if it does not exist
  raw: "groupadd {{ group_name }}"
  when: group_check.rc != 0

- name: Create a user account
  raw: "useradd -m -d {{ home_dir }} -c {{ comment | default('') }} -s {{ shell }} -g {{ group_name }} -p $(openssl passwd {{ password }}) {{ username }}"
