# tasks file for iteasy.ansible.roles.account_manager
---
- name: Set group_name to group or username
  set_fact:
    group_name: "{{ group if group is defined and group != '' else username }}"

- name: Set home_dir to default if not defined or empty
  set_fact:
    home_dir: "{{ home_dir if home_dir is defined and home_dir != '' else '/home/' ~ username }}"

- name: Debug the group_name and home_dir
  debug:
    msg:
      - "group_name is set to: {{ group_name }}"
      - "home_dir is set to: {{ home_dir }}"

- name: Check if group exists
  command: "getent group {{ group_name }}"
  register: group_check
  failed_when: false
  changed_when: false

- name: Create the group if it does not exist
  group:
    name: "{{ group_name }}"
    state: present
  when: group_check.rc != 0

- name: Create a user account
  user:
    name: "{{ username }}"
    password: "{{ password | default('') }}"
    home: "{{ home_dir }}"
    shell: "{{ shell }}"
    group: "{{ group_name }}"
    state: present
