# tasks file for iteasy.ansible.roles.account_manager
---
- name: Create a group if it does not exist
  group:
    name: "{{ group | default(username) }}"
    state: present
    
- name: Create a user account
  user:
    name: "{{ username }}"
    password: "{{ password | default('') }}"
    home: "{{ home_dir }}"
    shell: "{{ shell }}"
    group: "{{ group }}"
    state: present
