# tasks file for iteasy.ansible.roles.account_manager
---
- name: Check if the user exists
  command: "getent passwd {{ username }}"
  register: user_check
  failed_when: false
  changed_when: false

- name: Fail if the user does not exist
  fail:
    msg: "The user {{ username }} does not exist."
  when: user_check.rc != 0

- name: Delete user account
  user:
    name: "{{ username }}"
    state: absent
    remove: "{{ remove_home | default(false) }}"
  when: user_check.rc == 0

# - name: Delete user mail spool
#   when: mail_spool
#   file:
#     path: "{{ mail_spool_path }}"
#     state: absent
