---
# tasks file for iteasy.ansible.roles.account_manager
- name: Check if action is defined and valid
  fail:
    msg: "Invalid or missing 'action' variable. It must be 'create', 'update', or 'delete'."
  when: action not in ['create', 'update', 'delete']
  
- name: Include raw-based tasks if Python is less than 3
  ansible.builtin.include_tasks: "{{ action }}-raw_tasks.yml"
