---
# raw_tasks.yml - Update User

- name: Check if the user exists
  raw: "getent passwd {{ username }}"
  register: user_check
  failed_when: false
  changed_when: false

- name: Fail if the user does not exist
  fail:
    msg: "The user {{ username }} does not exist."
  when: user_check.rc != 0

- name: Debug the group_name, home_dir, shell, and password
  debug:
    msg:
      - "shell is set to: {{ shell }}"
      - "password is set to: {{ password }}"

- name: Update user password
  raw: "usermod -p $(openssl passwd {{ password }}) {{ username }}"
  when: password is defined and password != ''

- name: Update user group
  raw: "usermod -aG {{ group_name }} {{ username }}"
  when: group_name is defined and group_name != ''

- name: Update user shell
  raw: "chsh -s {{ shell }} {{ username }}"
  when: shell is defined and shell != ''
