---
# raw_tasks.yml - Update User

- name: Check if the user exists
  raw: "getent passwd {{ username }}"
  register: user_check
  failed_when: false
  changed_when: false

- name: Fail if the user does not exist
  fail:
    msg: "The user {{ username }} does not exist."
  when: user_check.rc != 0

- name: Update user password
  raw: "usermod -p $(openssl passwd -6 {{ password }}) {{ username }}"
  when: password is defined and password is not none

- name: Update user group
  raw: "usermod -aG {{ group }} {{ username }}"
  when: group is defined and group is not none

- name: Update user shell
  raw: "chsh -s {{ shell }} {{ username }}"
  when: shell is defined and shell is not none
